import bcrypt from 'bcryptjs';
const data = {
	users: [
		{
			name: 'Zlatko',
			email: 'zlatko@zlatkonikoloski.com',
			password: bcrypt.hashSync('123456789', 10),
			isAdmin: true,
		},
		{
			name: 'John',
			email: 'test@zlatkonikoloski.com',
			password: bcrypt.hashSync('123456789', 10),
			isAdmin: false,
		},
	],
	products: [
		{
			name: 'Apple MacBook Pro',
			category: 'Laptop',
			image: '/images/p1.jpg',
			price: 1200,
			countInStock: 10,
			brand: 'Apple',
			rating: 4.5,
			numReviews: 10,
			description: 'High quality product',
		},
		{
			name: 'Apple iPhone XS',
			category: 'Phones',
			image: '/images/p2.jpg',
			price: 1100,
			countInStock: 5,
			brand: 'Apple',
			rating: 4.0,
			numReviews: 12,
			description: 'High quality product',
		},
		{
			name: 'Apple iPad',
			category: 'Tablets',
			image: '/images/p3.jpg',
			price: 520,
			countInStock: 0,
			brand: 'Apple',
			rating: 4.8,
			numReviews: 17,
			description: 'High quality product',
		},
		{
			name: 'Samsung S20',
			category: 'Phones',
			image: '/images/p4.jpg',
			price: 1200,
			countInStock: 15,
			brand: 'Samsung',
			rating: 4.5,
			numReviews: 14,
			description: 'High quality product',
		},
		{
			name: 'Huawei P30 Pro',
			category: 'Phone',
			image: '/images/p5.jpg',
			price: 650,
			countInStock: 15,
			brand: 'Huawei',
			rating: 4.5,
			numReviews: 10,
			description: 'High quality product',
		},
		{
			name: 'iMac Pro',
			category: 'Desktop',
			image: '/images/p6.jpg',
			price: 1399,
			countInStock: 10,
			brand: 'Apple',
			rating: 3.5,
			numReviews: 15,
			description: 'High quality product',
		},
		{
			name: 'Huawei Mate 40 Pro',
			category: 'Phone',
			image: '/images/p7.jpg',
			price: 699,
			countInStock: 10,
			brand: 'Huawei',
			rating: 3.5,
			numReviews: 15,
			description: 'High quality product',
		},
	],
};
export default data;
