import bcrypt from 'bcryptjs';
const data = {
	users: [
		{
			name: 'Zlatko',
			email: 'zlatko@zlatkonikoloski.com',
			password: bcrypt.hashSync('123456789', 10),
			isAdmin: true,
		},
		{
			name: 'John',
			email: 'test@zlatkonikoloski.com',
			password: bcrypt.hashSync('123456789', 10),
			isAdmin: false,
		},
	],
	products: [
		{
			name: 'Nike Slim Shirt',
			category: 'Shirts',
			image: '/images/p1.jpg',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'High quality product',
		},
		{
			name: 'Adidas Fit Shirt',
			category: 'Shirts',
			image: '/images/p2.jpg',
			price: 100,
			countInStock: 5,
			brand: 'Adidas',
			rating: 4.0,
			numReviews: 12,
			description: 'High quality product',
		},
		{
			name: 'Lacoste Free Shirt',
			category: 'Shirts',
			image: '/images/p3.jpg',
			price: 220,
			countInStock: 0,
			brand: 'Lacoste',
			rating: 4.8,
			numReviews: 17,
			description: 'High quality product',
		},
		{
			name: 'Nike Slim Pant',
			category: 'Pants',
			image: '/images/p4.jpg',
			price: 120,
			countInStock: 15,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 14,
			description: 'High quality product',
		},
		{
			name: 'Puma Slim Pants',
			category: 'Pants',
			image: '/images/p5.jpg',
			price: 65,
			countInStock: 15,
			brand: 'Puma',
			rating: 4.5,
			numReviews: 10,
			description: 'High quality product',
		},
		{
			name: 'Adidas Fit Pants',
			category: 'Pants',
			image: '/images/p1.jpg',
			price: 139,
			countInStock: 10,
			brand: 'Adidas',
			rating: 3.5,
			numReviews: 15,
			description: 'High quality product',
		},
	],
};
export default data;
